### ISSUE TITLE
Stores wrong value for 9, 10, 13

### ISSUE THREAD

**Issue by b-blake** [adafruit/Adafruit_CircuitPython_24LC32#7]
For some reason the library is converting the 9, 10, 13 to TAB, NEW_LINE, CARRAGE_RETURN and storing the "\" character, 0x53, into the EEPROM.

`   eeprom[0x10] = 9
    print(eeprom[0x10])
    eeprom[0x10:0x16] = [9, 10, 13, 3, 8, 1]
    print(eeprom[0x10:0x18])`

EEPROM Dump:
`0x0010 | 0x5C 0x03 0x08 0x01 0xFF 0xFF 0xFF 0xFF`

The output shows:
`bytearray(b'\t')
bytearray(b'\t\n\r\x03\x08\x01\xff\xff')`

How do I get an output "stuff=eeprom(0x10:0x18)" other than in a  bytearray?

Bruce

**Comment by dhalbert** [comment]
`\x09` is exactly the same bits as `\t`, and similarly for the other characters. It's just that when it can interpret a byte as a character, it prints that character, rather than `\xnn`.

**Comment by b-blake** [comment]
My mistake:  Forget all after Hello.

**Comment by b-blake** [comment]
Dan,

I know "Consistency is the bane of a narrow mind."

If \t,  \n,  \r  are shown in bytearray, shouldn't  \b and \f also be shown?

\b aka Back_Space aka 0x08 is recognized in print("\b") and the cursor moves back one space.
\f aka Form_Feed aka Clear_Screen aka 0x0C is recognized in print("\f") and the REPL screen is cleared.

Bruce

**Comment by tekktrik** [comment]
@dhalbert thoughts on this?  I'm going through issues and saw this, and I'm pretty sure it's specific to the core and not this repo.

**Comment by FoamyGuy** [comment]
If I am understanding correctly, it looks to me that CircuitPython behavior matches that of CPython.

CircuitPython 9.2.0-alpha.2351:
```
>>> b = bytearray(b"\x0A\x09\x08\x0C")
>>> print(b)
bytearray(b'\n\t\x08\x0c')
```

CPython 3.12.3:
```
>>> b = bytearray(b"\x0A\x09\x08\x0C")
>>> print(b)
bytearray(b'\n\t\x08\x0c')
```

I'm going to close this, because I don't think we'd want to deviate from CPython behavior if possible. 

If I've misunderstood something or there is still some other proposal that applies to the core please feel free to re-open this or make a new issue over in the core repo.
